# configs/default.yaml

# data paths
data_stereo:
  raw_dir: ../data_stereo/raw
  proc_dir: ../data_stereo/processed

data_vo:
  base_dir: data_vo/dataset
  calib_dir: data_vo/dataset
  sequence: '01'
  cam: 0

# feature params
feature:
  type: SuperPoint            # ORB | SIFT | SuperPoint
  n_features: 1000
  superpoint:
    keypoint_threshold: 0.005
    device: cuda

# matcher params
matcher:
  type: SuperGlue             # BF | SuperGlue
  ratio_test: 0.75
  max_row_diff: 20
  superglue:
    weights: outdoor
    sinkhorn_iterations: 50
    match_threshold: 0.5
    device: cuda

# RANSAC / pose
ransac:
  prob: 0.999
  thresh: 2.0

# smoothing for EKF
smoothing:
  alpha: 0.10
  rot_thresh_deg: 5.0
  warmup_frames: 15

# grid-based match collection
collection:
  grid_rows:    8
  grid_cols:   16
  max_per_cell: 200

gnc:
  max_iters: 20

# fisheye camera intrinsics for checkerboard undistortion/matching
intrinsics:
  K: [[550.0395,   0.0,   960.0],
      [  0.0, 533.372225, 768.0],
      [  0.0,    0.0,     1.0]]
  D: [0.0017168675275541325,0.0080394521025418,-0.006041718283931211,0.001409880154695331]
  height: 1536
  width: 1920
